name: Bug Fix
description: Fix a bug in an existing project
title: "[BUGFIX] "
labels: [bug-fix]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping fix a bug!
        Please provide as much detail as possible about the bug and your fix.

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: Name of the project where the bug was found
      placeholder: "e.g., job_searching_agent"
    validations:
      required: true

  - type: dropdown
    id: project-directory
    attributes:
      label: Project Directory
      description: Select the directory where the bug was found
      options:
        - advance_ai_agents
        - mcp_ai_agents
        - rag_apps
        - starter_ai_agents
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of the bug
      placeholder: "Describe the bug in detail..."
    validations:
      required: true

  - type: textarea
    id: fix-description
    attributes:
      label: Fix Description
      description: Describe the changes made to fix the bug
      placeholder: "How did you fix the bug?"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. 
        2. 
        3.
      render: bash
    validations:
      required: true

  - type: textarea
    id: testing-done
    attributes:
      label: Testing Done
      description: Describe how you tested the fix
      placeholder: "What tests did you run to verify the fix?"
    validations:
      required: true

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files
      description: List the files that were modified
      placeholder: |
        - file1.py
        - file2.py
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the bug and fix
      placeholder: "Add screenshots here..."

  - type: checkboxes
    id: fix-checklist
    attributes:
      label: Fix Checklist
      description: Please check all that apply
      options:
        - label: Bug is reproducible in the current version
          required: true
        - label: Fix has been tested in the affected environment
          required: true
        - label: All existing tests pass
          required: true
        - label: New tests added (if applicable)
          required: true
        - label: No new bugs introduced
          required: true
        - label: Documentation updated if necessary
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the bug and fix
      placeholder: "Any additional information that might be helpful..."
