name: Project Addition
description: Add a new project to the repository
title: "[PROJECT] "
labels: [project-addition]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new project!
        Please provide as much detail as possible to help us review your submission.

  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: Use descriptive name with underscores (e.g., job_searching_agent)
      placeholder: "e.g., job_searching_agent"
    validations:
      required: true

  - type: dropdown
    id: target-directory
    attributes:
      label: Target Directory
      description: Select the appropriate directory for the project
      options:
        - advance_ai_agents
        - mcp_ai_agents
        - rag_apps
        - starter_ai_agents
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Provide a detailed description of your project
      placeholder: "What does your project do? Who is it for?"
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: List key technical aspects of your project
      placeholder: |
        - Primary Language/Framework:
        - Key Dependencies:
        - API Requirements:
    validations:
      required: true

  - type: textarea
    id: installation-steps
    attributes:
      label: Installation Steps
      description: Provide step-by-step installation instructions
      placeholder: |
        1. 
        2. 
        3.
      render: bash
    validations:
      required: true

  - type: textarea
    id: usage-examples
    attributes:
      label: Usage Examples
      description: Provide code examples or usage instructions
      placeholder: |
        ```python
        # Example code here
        ```
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List all dependencies with versions
      placeholder: |
        package1==1.0.0
        package2==2.0.0
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Demo
      description: Add screenshots or GIFs of your project in action
      placeholder: "Add screenshots here..."

  - type: checkboxes
    id: implementation-checklist
    attributes:
      label: Implementation Checklist
      description: Please check all that apply
      options:
        - label: Project name follows naming convention (descriptive with underscores)
          required: true
        - label: Added to the correct directory
          required: true
        - label: Includes comprehensive README.md
          required: true
        - label: Code follows project structure and conventions
          required: true
        - label: All dependencies are properly listed in requirements.txt
          required: true
        - label: Added appropriate documentation
          required: true
        - label: Code is properly formatted and linted
          required: true
        - label: Added necessary tests (if applicable)
          required: true

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any other information that might be helpful
      placeholder: "Any additional context or information..."
