[project]
name = "database-mcp-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "agno>=1.7.10",
    "mcp>=1.12.4",
    "openai>=1.99.9",
]
